/**
 * 常用中文名字词典。
 *
 * 这里用于给 `pinyin2ChineseV2` 提供更贴近日常输入法的姓名候选。
 * 词条以高频姓氏、常见双字名、叠字名和常见全名为主。
 *
 * key 使用不带分隔符的全拼形式，例如：
 * - zhangsan
 * - lixiaolong
 * - wangxiaoming
 */
const commonNames: Record<string, string[]> = {
  zhangsan: ['张三'],
  lisi: ['李四'],
  wangwu: ['王五'],
  zhaoliu: ['赵六'],

  xiaoming: ['小明'],
  xiaohong: ['小红'],
  xiaoli: ['小丽'],
  xiaomei: ['小美'],
  xiaofang: ['小芳'],
  xiaojie: ['小杰'],
  xiaoyu: ['小雨', '小宇', '小玉'],
  xiaolong: ['小龙'],
  xiaoxia: ['小夏'],
  xiaoxue: ['小雪'],
  xiaoyue: ['小月'],
  xiaoqiang: ['小强'],
  xiaohui: ['小辉'],
  xiaoqian: ['小倩'],
  xiaoxin: ['小欣', '小鑫'],
  xiaorui: ['小瑞'],
  xiaotao: ['小涛'],
  xiaoyan: ['小燕'],
  xiaojuan: ['小娟'],
  xiaolan: ['小兰'],
  xiaojun: ['小军'],
  xiaofei: ['小飞'],

  leilei: ['磊磊', '蕾蕾', '雷雷'],
  tingting: ['婷婷'],
  nanan: ['楠楠', '南南'],
  jingjing: ['晶晶', '静静'],
  yanyan: ['妍妍'],
  mengmeng: ['萌萌', '梦梦', '蒙蒙'],
  yuanyuan: ['媛媛', '圆圆', '园园'],
  dongdong: ['东东'],
  chenchen2: ['晨晨', '辰辰'],
  feifei: ['菲菲', '飞飞'],
  lanlan: ['兰兰'],
  qianqian: ['倩倩', '茜茜'],
  xinxin: ['欣欣', '鑫鑫', '心心'],
  ruirui: ['瑞瑞', '睿睿'],
  haohao: ['昊昊'],
  binbin: ['彬彬', '斌斌'],
  pengpeng: ['鹏鹏'],
  junjun: ['军军', '俊俊'],
  taotao: ['涛涛'],
  yueyue: ['月月', '悦悦'],
  linlin: ['琳琳', '林林'],
  nanan2: ['娜娜'],

  weiguo: ['伟国'],
  jianguo: ['建国'],
  jianhua: ['建华'],
  guoqiang: ['国强'],
  guohua: ['国华'],
  zhigang: ['志刚'],
  zhiyong: ['志勇'],
  zhijun: ['志军'],
  jianjun: ['建军'],
  jianming: ['建明'],
  weimin: ['卫民'],
  aimin: ['爱民'],
  guoping: ['国平'],
  guoliang: ['国良'],
  xiaoping: ['晓萍', '小平'],
  xiulan: ['秀兰'],
  xiuying: ['秀英'],
  guizhen: ['桂珍'],
  yulan: ['玉兰'],
  yumei: ['玉梅'],
  hongmei: ['红梅'],
  yanhong: ['艳红'],
  cuiping: ['翠萍'],
  shufen: ['淑芬'],
  limei: ['丽梅'],
  lihua: ['李华', '丽华'],
  minmin: ['敏敏'],

  zhangwei: ['张伟'],
  zhangmin: ['张敏'],
  zhangli: ['张丽'],
  zhanglei: ['张磊'],
  zhangjing: ['张静'],
  zhangyan: ['张燕'],
  zhangtao: ['张涛'],
  zhanghao: ['张浩'],
  zhangyu: ['张宇'],
  zhangrui: ['张瑞'],
  zhangyang: ['张洋'],
  zhangpeng: ['张鹏'],
  zhangxin: ['张鑫', '张欣'],
  zhangchen: ['张晨', '张辰'],
  zhangqi: ['张琪', '张琦'],
  zhangxuan: ['张轩'],
  zhangting: ['张婷'],
  zhangjiajia: ['张佳佳'],
  zhangxiaoming: ['张小明'],
  zhangqiang: ['张强'],
  zhanghui: ['张辉'],
  zhangyue: ['张悦'],
  zhangqian: ['张倩'],
  zhangjuan: ['张娟'],
  zhangxiaoli: ['张小丽'],
  zhangxiaohong: ['张小红'],
  zhangyifan: ['张一凡'],
  zhangyihan: ['张一涵'],
  zhangzixuan: ['张子轩'],
  zhangzihan: ['张子涵'],
  zhangyuxin: ['张雨欣'],
  zhangxinyi: ['张欣怡'],
  zhangruoxi: ['张若曦'],
  zhangjingyi: ['张婧怡'],
  zhangyuxuan: ['张雨轩'],
  zhangyutong: ['张雨彤'],
  zhanghaoran: ['张浩然'],
  zhangruohan: ['张若涵'],
  zhangchenxi: ['张晨曦'],
  zhangmuchen: ['张沐宸'],
  zhangshiyu: ['张诗雨'],
  zhangzeyu: ['张泽宇'],
  zhangyichen: ['张奕辰'],
  zhangzirui: ['张梓睿'],

  liwei: ['李伟'],
  limin: ['李敏'],
  lili: ['李丽'],
  lilei: ['李雷'],
  liting: ['李婷'],
  liujing: ['刘静'],
  liuyan: ['刘燕'],
  liuyang: ['刘洋'],
  liuyang2: ['李杨'],
  lihao: ['李浩'],
  liyu: ['李雨', '李宇'],
  lixin: ['李鑫', '李欣'],
  lichen: ['李晨', '李辰'],
  lirui: ['李瑞'],
  lijia: ['李佳'],
  lijiajia: ['李佳佳'],
  lixiaolong: ['李小龙'],
  liumang: ['刘忙'],
  liqiang: ['李强'],
  lihui: ['李辉'],
  liyue: ['李悦'],
  liqian: ['李倩'],
  lijuan: ['李娟'],
  liyifan: ['李一凡'],
  liyihan: ['李一涵'],
  lizixuan: ['李子轩'],
  lizihan: ['李子涵'],
  liyuxin: ['李雨欣'],
  lixinyi: ['李欣怡'],
  liruoxi: ['李若曦'],
  lijingyi: ['李婧怡'],
  liyuxuan: ['李雨轩'],
  liyutong: ['李雨彤'],
  lihaoran: ['李浩然'],
  liruohan: ['李若涵'],
  lichenxi: ['李晨曦'],
  limuchen: ['李沐宸'],
  lishiyu: ['李诗雨'],
  lizeyu: ['李泽宇'],
  liyichen: ['李奕辰'],
  lixirui: ['李梓睿'],

  wangwei: ['王伟'],
  wangfang: ['王芳'],
  wangjing: ['王静'],
  wangmin: ['王敏'],
  wangli: ['王丽'],
  wanglei: ['王磊'],
  wangtao: ['王涛'],
  wangyan: ['王燕'],
  wangyu: ['王宇', '王雨'],
  wanghao: ['王浩'],
  wangrui: ['王瑞'],
  wangxin: ['王鑫', '王欣'],
  wangqiang: ['王强'],
  wangpeng: ['王鹏'],
  wangjiajia: ['王佳佳'],
  wangxiaoming: ['王小明'],
  wanghui: ['王辉'],
  wangyue: ['王悦'],
  wangqian: ['王倩'],
  wangjuan: ['王娟'],
  wangyifan: ['王一凡'],
  wangyihan: ['王一涵'],
  wangzixuan: ['王子轩'],
  wangzihan: ['王子涵'],
  wangyuxin: ['王雨欣'],
  wangxinyi: ['王欣怡'],
  wangruoxi: ['王若曦'],
  wangjingyi: ['王婧怡'],
  wangyuxuan: ['王雨轩'],
  wangyutong: ['王雨彤'],
  wanghaoran: ['王浩然'],
  wangruohan: ['王若涵'],
  wangchenxi: ['王晨曦'],
  wangmuchen: ['王沐宸'],
  wangshiyu: ['王诗雨'],
  wangzeyu: ['王泽宇'],
  wangyichen: ['王奕辰'],
  wangzirui: ['王梓睿'],

  zhaowei: ['赵伟'],
  zhaomin: ['赵敏'],
  zhaoli: ['赵丽'],
  zhaolei: ['赵磊'],
  zhaojing: ['赵静'],
  zhaoyan: ['赵燕'],
  zhaoyong: ['赵勇'],
  zhaohui: ['赵辉'],
  zhaoxin: ['赵鑫', '赵欣'],
  zhaorui: ['赵瑞'],
  zhaoyue: ['赵悦'],
  zhaoqian: ['赵倩'],
  zhaoqiang: ['赵强'],
  zhaohui2: ['赵慧'],
  zhaojuan: ['赵娟'],
  zhaoyifan: ['赵一凡'],
  zhaozihan: ['赵子涵'],
  zhaoyuxuan: ['赵雨轩'],
  zhaoyutong: ['赵雨彤'],
  zhaohaoran: ['赵浩然'],
  zhaoruohan: ['赵若涵'],

  liuwei: ['刘伟'],
  liuyang3: ['刘阳'],
  liumin: ['刘敏'],
  liujie: ['刘杰'],
  liuqiang: ['刘强'],
  liutao: ['刘涛'],
  liuhui: ['刘辉'],
  liuxin: ['刘鑫', '刘欣'],
  liurui: ['刘瑞'],
  liuyue: ['刘悦'],
  liuxuan: ['刘轩'],
  liujiajia: ['刘佳佳'],
  liuhao: ['刘浩'],
  liuqiang2: ['刘强'],
  liuhui2: ['刘慧'],
  liuqian: ['刘倩'],
  liujuan: ['刘娟'],
  liuyifan: ['刘一凡'],
  liuzihan: ['刘子涵'],
  liuyuxin: ['刘雨欣'],
  liuyuxuan: ['刘雨轩'],
  liuyutong: ['刘雨彤'],
  liuhaoran: ['刘浩然'],
  liuruohan: ['刘若涵'],
  liuchenxi: ['刘晨曦'],
  liumuchen: ['刘沐宸'],

  chenwei: ['陈伟'],
  chenjie: ['陈杰'],
  chenhao: ['陈浩'],
  chenyu: ['陈宇', '陈雨'],
  chenchen: ['陈晨'],
  chenli: ['陈丽'],
  chenjing: ['陈静'],
  chenting: ['陈婷'],
  chenrui: ['陈瑞'],
  chenxin: ['陈鑫', '陈欣'],
  chenjiajia: ['陈佳佳'],
  chenqiang: ['陈强'],
  chenhui: ['陈辉'],
  chenyue: ['陈悦'],
  chenqian: ['陈倩'],
  chenjuan: ['陈娟'],
  chenyifan: ['陈一凡'],
  chenzihan: ['陈子涵'],
  chenyuxin: ['陈雨欣'],
  chenxinyi: ['陈欣怡'],
  chenyuxuan: ['陈雨轩'],
  chenyutong: ['陈雨彤'],
  chenhaoran: ['陈浩然'],
  chenruohan: ['陈若涵'],
  chenchenxi: ['陈晨曦'],
  chenmuchen: ['陈沐宸'],

  yangyang: ['杨洋'],
  yangwei: ['杨威'],
  yangfan: ['杨帆'],
  yangrui: ['杨瑞'],
  yanghao: ['杨浩'],
  yangjing: ['杨静'],
  yangmin: ['杨敏'],
  yangliu: ['杨柳'],
  yangjie: ['杨杰'],
  yanghui: ['杨辉'],
  yangyue: ['杨悦'],
  yangqian: ['杨倩'],
  yangjuan: ['杨娟'],
  yangyifan: ['杨一凡'],
  yangzihan: ['杨子涵'],
  yangyuxin: ['杨雨欣'],
  yangyuxuan: ['杨雨轩'],
  yangyutong: ['杨雨彤'],
  yanghaoran: ['杨浩然'],
  yangruohan: ['杨若涵'],

  huangwei: ['黄伟'],
  huangmin: ['黄敏'],
  huangjing: ['黄静'],
  huangli: ['黄丽'],
  huanghao: ['黄浩'],
  huangrui: ['黄瑞'],
  huangjie: ['黄杰'],
  huanghui: ['黄辉'],
  huangyue: ['黄悦'],
  huangqian: ['黄倩'],
  huangjuan: ['黄娟'],
  huangyifan: ['黄一凡'],
  huangzihan: ['黄子涵'],
  huangyuxuan: ['黄雨轩'],
  huangyutong: ['黄雨彤'],
  huanghaoran: ['黄浩然'],

  zhoujie: ['周杰'],
  zhouwei: ['周伟'],
  zhoumin: ['周敏'],
  zhouyang: ['周洋'],
  zhouting: ['周婷'],
  zhourui: ['周瑞'],
  zhouhao: ['周浩'],
  zhouhui: ['周辉'],
  zhouyue: ['周悦'],
  zhouqian: ['周倩'],
  zhoujuan: ['周娟'],
  zhouyifan: ['周一凡'],
  zhouzihan: ['周子涵'],
  zhouyuxuan: ['周雨轩'],
  zhouhaoran: ['周浩然'],

  wujing: ['吴静'],
  wulei: ['吴磊'],
  wuhao: ['吴昊'],
  wuting: ['吴婷'],
  wuxin: ['吴昕'],
  wuwei: ['吴伟'],
  wumin: ['吴敏'],
  wuhui: ['吴辉'],
  wuqian: ['吴倩'],
  wujuan: ['吴娟'],
  wuyifan: ['吴一凡'],
  wuzihan: ['吴子涵'],
  wuyuxuan: ['吴雨轩'],
  wuhaoran: ['吴浩然'],

  xukai: ['徐凯'],
  xumin: ['徐敏'],
  xuting: ['徐婷'],
  xulei: ['徐磊'],
  xujing: ['徐静'],
  xuwei: ['徐伟'],
  xuhao: ['徐浩'],
  xuhui: ['徐辉'],
  xuqian: ['徐倩'],
  xujuan: ['徐娟'],
  xuyifan: ['徐一凡'],
  xuzihan: ['徐子涵'],
  xuyuxuan: ['徐雨轩'],
  xuhaoran: ['徐浩然'],

  sunwei: ['孙伟'],
  sunli: ['孙莉', '孙丽'],
  sunhao: ['孙浩'],
  sunrui: ['孙瑞'],
  sunjiajia: ['孙佳佳'],
  sunmin: ['孙敏'],
  sunhui: ['孙辉'],
  sunqian: ['孙倩'],
  sunjuan: ['孙娟'],
  sunyifan: ['孙一凡'],
  sunzihan: ['孙子涵'],
  sunyuxuan: ['孙雨轩'],
  sunhaoran: ['孙浩然'],

  zhengwei: ['郑伟'],
  zhengmin: ['郑敏'],
  zhenghao: ['郑浩'],
  zhengting: ['郑婷'],
  zhengrui: ['郑瑞'],
  zhengyifan: ['郑一凡'],
  zhengyuxuan: ['郑雨轩'],
  zhenghaoran: ['郑浩然'],

  xiewei: ['谢伟'],
  xiemin: ['谢敏'],
  xiehao: ['谢浩'],
  xieting: ['谢婷'],
  xierui: ['谢瑞'],
  xieyuxuan: ['谢雨轩'],
  xiehaoran: ['谢浩然'],

  guowei: ['郭伟'],
  guomin: ['郭敏'],
  guohao: ['郭浩'],
  guoting: ['郭婷'],
  guorui: ['郭瑞'],
  guoyuxuan: ['郭雨轩'],
  guohaoran: ['郭浩然'],

  hewei: ['何伟'],
  hemin: ['何敏'],
  hehao: ['何浩'],
  heting: ['何婷'],
  herui: ['何瑞'],
  heyuxuan: ['何雨轩'],
  hehaoran: ['何浩然'],

  luwei: ['卢伟'],
  lumin: ['卢敏'],
  luhao: ['卢浩'],
  luting: ['卢婷'],
  lurui: ['卢瑞'],
  luyuxuan: ['卢雨轩'],
  luhaoran: ['卢浩然'],

  ouyangnana: ['欧阳娜娜'],
  ouyangjing: ['欧阳靖'],
  simayi: ['司马懿'],
  zhugeliang: ['诸葛亮'],
  shangguanwaner: ['上官婉儿'],
  simaxiangru: ['司马相如'],

  zhoujielun: ['周杰伦'],
  liuyifei: ['刘亦菲'],
  yangmi: ['杨幂'],
  dilireba: ['迪丽热巴'],
  zhaoliying: ['赵丽颖'],
  wangyibo: ['王一博'],
  xiaozhan: ['肖战'],
  yiyangqianxi: ['易烊千玺'],
  hulei: ['胡磊'],
  caixukun: ['蔡徐坤'],
  wangjunkai: ['王俊凯'],
  wangyuan: ['王源'],
  yijianlian: ['易建联'],

  mayun: ['马云'],
  liuyan2: ['刘艳'],
  zhouenlai: ['周恩来'],
  dengxiaoping: ['邓小平'],
  liyanhong: ['李彦宏'],
  mahuateng: ['马化腾'],
  renzhengfei: ['任正非'],
  dongmingzhu: ['董明珠'],
};

export default commonNames;
