/**
 * 中国地理位置高频词典。
 *
 * 这里单独维护省 / 自治区 / 直辖市 / 特别行政区、
 * 省会城市、常见地级市，以及部分高频区县名称。
 *
 * key 使用不带分隔符的全拼形式，例如：
 * - beijing
 * - guangdongsheng
 * - chaoyangqu
 */
const geographyPhrases: Record<string, string[]> = {
  zhongguo: ['中国'],
  zhonghuarenmingongheguo: ['中华人民共和国'],
  huabei: ['华北'],
  dongbei: ['东北'],
  huadong: ['华东'],
  huazhong: ['华中'],
  huanan: ['华南'],
  xinan: ['西南'],
  xibei: ['西北'],
  gangao: ['港澳'],
  gangaodawanqu: ['港澳大湾区'],
  jingjinji: ['京津冀'],
  changsanjiao: ['长三角'],
  zhusanjiao: ['珠三角'],

  beijing: ['北京'],
  beijingshi: ['北京市'],
  dongchengqu: ['东城区'],
  xichengqu: ['西城区'],
  chaoyangqu: ['朝阳区'],
  haidianqu: ['海淀区'],
  fengtaiqu: ['丰台区'],
  shijingshanqu: ['石景山区'],
  tongzhouqu: ['通州区'],
  changpingqu: ['昌平区'],
  daxingqu: ['大兴区'],
  shunyiqu: ['顺义区'],
  fangshanqu: ['房山区'],
  mentougouqu: ['门头沟区'],
  pingguqu: ['平谷区'],
  huairouqu: ['怀柔区'],
  miyunqu: ['密云区'],
  yanqingqu: ['延庆区'],

  tianjin: ['天津'],
  tianjinshi: ['天津市'],
  hepingqu: ['和平区'],
  hedongqu: ['河东区'],
  hexiqu: ['河西区'],
  nankaiqu: ['南开区'],
  hebeiqu: ['河北区'],
  hongqiaoqu: ['红桥区'],
  binhaixinqu: ['滨海新区'],
  xiqingqu: ['西青区'],
  jinnanqu: ['津南区'],
  beichenqu: ['北辰区'],
  wuqingqu: ['武清区'],
  baodiqu: ['宝坻区'],

  shanghai: ['上海'],
  shanghaishi: ['上海市'],
  huangpuqu: ['黄浦区'],
  xuhuiqu: ['徐汇区'],
  changningqu: ['长宁区'],
  jinganqu: ['静安区'],
  putuoqu: ['普陀区'],
  hongkouqu: ['虹口区'],
  yangpuqu: ['杨浦区'],
  pudongxinqu: ['浦东新区'],
  minhangqu: ['闵行区'],
  baoshanqu: ['宝山区'],
  jiadingqu: ['嘉定区'],
  jinshanqu: ['金山区'],
  songjiangqu: ['松江区'],
  qingpuqu: ['青浦区'],
  fengxianqu: ['奉贤区'],
  chongmingqu: ['崇明区'],

  chongqing: ['重庆'],
  chongqingshi: ['重庆市'],
  yuzhongqu: ['渝中区'],
  jiulongpoqu: ['九龙坡区'],
  nananqu: ['南岸区'],
  jiangbeiqu: ['江北区'],
  shapingbaqu: ['沙坪坝区'],
  dadukouqu: ['大渡口区'],
  beibeiqu: ['北碚区'],
  yubeiqu: ['渝北区'],
  bananqu: ['巴南区'],
  liangjiangxinqu: ['两江新区'],

  hebeisheng: ['河北省'],
  shijiazhuang: ['石家庄'],
  shijiazhuangshi: ['石家庄市'],
  tangshan: ['唐山'],
  qinhuangdao: ['秦皇岛'],
  handan: ['邯郸'],
  xingtai: ['邢台'],
  baoding: ['保定'],
  zhangjiakou: ['张家口'],
  chengde: ['承德'],
  cangzhou: ['沧州'],
  langfang: ['廊坊'],
  hengshui: ['衡水'],

  shanxisheng: ['山西省'],
  taiyuan: ['太原'],
  taiyuanshi: ['太原市'],
  datong: ['大同'],
  yangquan: ['阳泉'],
  changzhi: ['长治'],
  jincheng: ['晋城'],
  shuozhou: ['朔州'],
  jinzhong: ['晋中'],
  yuncheng: ['运城'],
  xinzhou: ['忻州'],
  linfen: ['临汾'],
  lvliang: ['吕梁'],

  neimenggu: ['内蒙古'],
  neimengguzizhiqu: ['内蒙古自治区'],
  huhehaote: ['呼和浩特'],
  baotou: ['包头'],
  wuhai: ['乌海'],
  chifeng: ['赤峰'],
  tongliao: ['通辽'],
  eerduosi: ['鄂尔多斯'],
  hulunbeier: ['呼伦贝尔'],
  bayannaoer: ['巴彦淖尔'],
  wulanchabu: ['乌兰察布'],

  liaoningsheng: ['辽宁省'],
  shenyang: ['沈阳'],
  dalian: ['大连'],
  anshan: ['鞍山'],
  fushun: ['抚顺'],
  benxi: ['本溪'],
  dandong: ['丹东'],
  jinzhou: ['锦州'],
  yingkou: ['营口'],
  fuxin: ['阜新'],
  liaoyang: ['辽阳'],
  panjin: ['盘锦'],
  tieling: ['铁岭'],
  chaoyangshi: ['朝阳市'],
  huludao: ['葫芦岛'],

  jilingsheng: ['吉林省'],
  changchun: ['长春'],
  jilinshi: ['吉林市'],
  siping: ['四平'],
  liaoyuan: ['辽源'],
  tonghua: ['通化'],
  baishan: ['白山'],
  songyuan: ['松原'],
  baicheng: ['白城'],
  yanbian: ['延边'],
  yanbianzhou: ['延边朝鲜族自治州'],

  heilongjiangsheng: ['黑龙江省'],
  haerbin: ['哈尔滨'],
  qiqihaer: ['齐齐哈尔'],
  jixi: ['鸡西'],
  hegang: ['鹤岗'],
  shuangyashan: ['双鸭山'],
  daqing: ['大庆'],
  yichunshi: ['伊春市'],
  jiamusi: ['佳木斯'],
  qitaihe: ['七台河'],
  mudanjiang: ['牡丹江'],
  heihe: ['黑河'],
  suihua: ['绥化'],

  jiangsusheng: ['江苏省'],
  nanjing: ['南京'],
  suzhou: ['苏州'],
  wuxi: ['无锡'],
  changzhou: ['常州'],
  zhenjiang: ['镇江'],
  nantong: ['南通'],
  yangzhou: ['扬州'],
  yancheng: ['盐城'],
  xuzhou: ['徐州'],
  lianyungang: ['连云港'],
  huaian: ['淮安'],
  suqian: ['宿迁'],
  taizhoujiangsu: ['泰州'],

  zhejiangsheng: ['浙江省'],
  hangzhou: ['杭州'],
  ningbo: ['宁波'],
  wenzhou: ['温州'],
  jiaxing: ['嘉兴'],
  huzhou: ['湖州'],
  shaoxing: ['绍兴'],
  jinhua: ['金华'],
  quzhou: ['衢州'],
  zhoushan: ['舟山'],
  taizhouzhejiang: ['台州'],
  lishui: ['丽水'],

  anhuisheng: ['安徽省'],
  hefei: ['合肥'],
  wuhu: ['芜湖'],
  bengbu: ['蚌埠'],
  huainan: ['淮南'],
  maanshan: ['马鞍山'],
  huaibei: ['淮北'],
  tongling: ['铜陵'],
  anqing: ['安庆'],
  huangshan: ['黄山'],
  chuzhou: ['滁州'],
  fuyanganhui: ['阜阳'],
  suzhouanhui: ['宿州'],
  liuan: ['六安'],
  bozhou: ['亳州'],
  chizhou: ['池州'],
  xuancheng: ['宣城'],

  fujiansheng: ['福建省'],
  fuzhou: ['福州'],
  xiamen: ['厦门'],
  quanzhou: ['泉州'],
  zhangzhou: ['漳州'],
  putian: ['莆田'],
  sanming: ['三明'],
  nanping: ['南平'],
  longyan: ['龙岩'],
  ningde: ['宁德'],

  jiangxisheng: ['江西省'],
  nanchang: ['南昌'],
  jingdezhen: ['景德镇'],
  pingxiang: ['萍乡'],
  jiujiang: ['九江'],
  xinyu: ['新余'],
  yingtan: ['鹰潭'],
  ganzhou: ['赣州'],
  jianshi: ['吉安市'],
  yichunjx: ['宜春'],
  fuzhoujx: ['抚州'],
  shangrao: ['上饶'],

  shandongsheng: ['山东省'],
  jinan: ['济南'],
  qingdao: ['青岛'],
  zibo: ['淄博'],
  zaozhuang: ['枣庄'],
  dongying: ['东营'],
  yantai: ['烟台'],
  weifang: ['潍坊'],
  jining: ['济宁'],
  taian: ['泰安'],
  weihai: ['威海'],
  rizhao: ['日照'],
  linyi: ['临沂'],
  dezhou: ['德州'],
  liaocheng: ['聊城'],
  binzhou: ['滨州'],
  heze: ['菏泽'],

  henansheng: ['河南省'],
  zhengzhou: ['郑州'],
  kaifeng: ['开封'],
  luoyang: ['洛阳'],
  pingdingshan: ['平顶山'],
  anyang: ['安阳'],
  hebishi: ['鹤壁市'],
  xinxiang: ['新乡'],
  jiaozuo: ['焦作'],
  puyang: ['濮阳'],
  xuchang: ['许昌'],
  luohe: ['漯河'],
  sanmenxia: ['三门峡'],
  nanyang: ['南阳'],
  shangqiu: ['商丘'],
  xinyang: ['信阳'],
  zhoukou: ['周口'],
  zhumadian: ['驻马店'],

  hubeisheng: ['湖北省'],
  wuhan: ['武汉'],
  huangshi: ['黄石'],
  shiyan: ['十堰'],
  yichunhubei: ['宜昌'],
  xiangyang: ['襄阳'],
  ezhou: ['鄂州'],
  jingmen: ['荆门'],
  xiaogan: ['孝感'],
  jingzhou: ['荆州'],
  huanggang: ['黄冈'],
  xianning: ['咸宁'],
  suizhou: ['随州'],
  enshi: ['恩施'],

  hunansheng: ['湖南省'],
  changsha: ['长沙'],
  zhuzhou: ['株洲'],
  xiangtan: ['湘潭'],
  hengyang: ['衡阳'],
  shaoyang: ['邵阳'],
  yueyang: ['岳阳'],
  changde: ['常德'],
  zhangjiajie: ['张家界'],
  yiyang: ['益阳'],
  chenzhou: ['郴州'],
  yongzhou: ['永州'],
  huaihua: ['怀化'],
  loudi: ['娄底'],
  xiangxi: ['湘西'],

  guangdongsheng: ['广东省'],
  guangzhou: ['广州'],
  shenzhen: ['深圳'],
  foshan: ['佛山'],
  dongguan: ['东莞'],
  zhongshan: ['中山'],
  zhuhai: ['珠海'],
  huizhou: ['惠州'],
  jiangmen: ['江门'],
  zhanjiang: ['湛江'],
  maoming: ['茂名'],
  zhaoqing: ['肇庆'],
  shantou: ['汕头'],
  jieyang: ['揭阳'],
  chaoshan: ['潮汕'],

  guangxizizhiqu: ['广西壮族自治区'],
  guangxi: ['广西'],
  nanning: ['南宁'],
  liuzhou: ['柳州'],
  guilin: ['桂林'],
  wuzhou: ['梧州'],
  beihai: ['北海'],
  fangchenggang: ['防城港'],
  qinzhou: ['钦州'],
  guigang: ['贵港'],
  yulinguangxi: ['玉林'],
  baise: ['百色'],
  hezhou: ['贺州'],

  hainansheng: ['海南省'],
  haikou: ['海口'],
  sanya: ['三亚'],
  sansha: ['三沙'],
  danzhou: ['儋州'],

  sichuansheng: ['四川省'],
  chengdu: ['成都'],
  mianyang: ['绵阳'],
  deyang: ['德阳'],
  luzhou: ['泸州'],
  yibin: ['宜宾'],
  leshan: ['乐山'],
  nanchongsi: ['南充'],
  dazhou: ['达州'],
  zigong: ['自贡'],
  panzhihua: ['攀枝花'],
  guangan: ['广安'],
  meishan: ['眉山'],

  guizhousheng: ['贵州省'],
  guiyang: ['贵阳'],
  liupanshui: ['六盘水'],
  zunyi: ['遵义'],
  anshungz: ['安顺'],
  bijie: ['毕节'],
  tongren: ['铜仁'],
  qiandongnan: ['黔东南'],
  qiannan: ['黔南'],
  qianxinan: ['黔西南'],

  yunnansheng: ['云南省'],
  kunming: ['昆明'],
  qujing: ['曲靖'],
  yuxi: ['玉溪'],
  baoshan: ['保山'],
  zhaotong: ['昭通'],
  lijiang: ['丽江'],
  puer: ['普洱'],
  lincang: ['临沧'],
  chuxiong: ['楚雄'],
  dali: ['大理'],
  xishuangbanna: ['西双版纳'],

  xizang: ['西藏'],
  xizangzizhiqu: ['西藏自治区'],
  lasa: ['拉萨'],
  rikaze: ['日喀则'],
  changdu: ['昌都'],
  linzhi: ['林芝'],
  shannanxz: ['山南'],

  shanxisheng2: ['陕西省'],
  xian: ['西安'],
  xianshi: ['西安市'],
  tongchuan: ['铜川'],
  baoji: ['宝鸡'],
  xianyang: ['咸阳'],
  weinan: ['渭南'],
  yanan: ['延安'],
  hanyin: ['汉阴'],
  hanzhong: ['汉中'],
  yulinshanxi: ['榆林'],
  ankang: ['安康'],
  shangluo: ['商洛'],

  gansusheng: ['甘肃省'],
  lanzhou: ['兰州'],
  jiayuguan: ['嘉峪关'],
  jinchang: ['金昌'],
  baiyin: ['白银'],
  tianshui: ['天水'],
  wuwei: ['武威'],
  zhangye: ['张掖'],
  pingliang: ['平凉'],
  jiuquan: ['酒泉'],
  qingyang: ['庆阳'],
  dingweishi: ['定西'],
  longnan: ['陇南'],

  qinghaisheng: ['青海省'],
  xining: ['西宁'],
  haidong: ['海东'],
  haibei: ['海北'],
  huangnan: ['黄南'],
  hainanqinghai: ['海南藏族自治州'],
  guoluo: ['果洛'],
  yushu: ['玉树'],
  haixi: ['海西'],

  ningxia: ['宁夏'],
  ningxiazizhiqu: ['宁夏回族自治区'],
  yinchuan: ['银川'],
  shizuishan: ['石嘴山'],
  wuzhong: ['吴忠'],
  guyuan: ['固原'],
  zhongweinx: ['中卫'],

  xinjiang: ['新疆'],
  xinjiangzizhiqu: ['新疆维吾尔自治区'],
  wulumuqi: ['乌鲁木齐'],
  kelamayi: ['克拉玛依'],
  tulufan: ['吐鲁番'],
  hami: ['哈密'],
  changji: ['昌吉'],
  yili: ['伊犁'],
  akesu: ['阿克苏'],
  kashi: ['喀什'],
  hetian: ['和田'],

  xianggang: ['香港'],
  xianggangtebiexingzhengqu: ['香港特别行政区'],
  jiulong: ['九龙'],
  xinjie: ['新界'],
  xianggangdao: ['香港岛'],

  aomen: ['澳门'],
  aomentebiexingzhengqu: ['澳门特别行政区'],

  taiwan: ['台湾'],
  taiwansheng: ['台湾省'],
  taibei: ['台北'],
  xinbei: ['新北'],
  taizhong: ['台中'],
  gaoxiong: ['高雄'],
  taonan: ['台南'],
  taoyuan: ['桃园'],
};

export default geographyPhrases;
