import type { ComponentDoc } from './types';
import { noTokens } from './shared';
import {
  UseContinuousTriggerDemo,
  UseHorizontalDragScrollDemo,
  UseInputDemo,
  UseIsMobileDemo,
  UseTouchClickGuardDemo,
} from './demos/hookDemos';

export const hookDocs: ComponentDoc[] = [
  {
    key: 'use-input',
    path: '/hooks/use-input',
    title: 'useInput',
    menuLabel: 'useInput',
    description: '核心输入联动 hook，负责接管输入框、候选词、控制键、按键事件和虚拟键盘交互状态。',
    importCode: `import { useInput } from 'rc-virtual-keyboard';`,
    usageCode: `import { useState } from 'react';\nimport { NumberKeyboard, keys, useInput } from 'rc-virtual-keyboard';\n\nexport default function Demo() {\n  const [value, setValue] = useState('');\n  const { onClick, onKeyDown, onKeyUp, isKeyActive } = useInput({\n    defaultActiveKeyboard: keys.numberType,\n  });\n\n  return (\n    <>\n      <input value={value} onChange={(e) => setValue(e.target.value)} />\n      <NumberKeyboard\n        onClick={onClick}\n        onKeyDown={onKeyDown}\n        onKeyUp={onKeyUp}\n        isKeyActive={isKeyActive}\n      />\n    </>\n  );\n}`,
    props: [
      { name: 'themeMode', type: 'string', defaultValue: 'light', description: '初始化主题模式' },
      { name: 'positionMode', type: 'string', defaultValue: 'float', description: '初始化位置模式' },
      { name: 'defaultActiveKeyboard', type: 'string', defaultValue: 'number', description: '默认激活的键盘类型' },
      { name: 'focusShow', type: 'boolean', defaultValue: 'autoPopup', description: '输入框聚焦时是否自动弹出键盘' },
      { name: 'useKeydownAudio', type: "'Y' | 'N'", defaultValue: 'Y', description: '是否开启按键音效' },
      { name: 'keydownAudioUrl', type: 'string', defaultValue: '/audio/typing-sound-02-229861.mp3', description: '按键音效资源地址' },
      { name: 'autoPopup', type: 'boolean', defaultValue: 'true', description: '兼容旧参数，等价于 focusShow' },
      { name: 'onChangeShow', type: '(visible: boolean) => void', defaultValue: '-', description: '控制键盘显隐' },
      { name: 'onPinyin2Chinese', type: '(value: string) => { pinyin: string; chinese: string[] }', defaultValue: '内置实现', description: '自定义拼音转汉字逻辑' },
      { name: 'onEnglishWords', type: '(value: string) => string[]', defaultValue: '内置实现', description: '自定义英文候选联想' },
      { name: 'onImageToWord', type: '(url: string, options?) => Promise<string[]>', defaultValue: '内置 tesseract.js', description: '自定义手写识别逻辑' },
    ],
    methods: [
      { name: 'onClick / onKeyDown / onKeyUp', signature: '(key: KeyboardAttributeType) => void', description: '直接传给键盘组件，完成输入、按下和抬起链路' },
      { name: 'onChangeInputMode', signature: "(mode: 'zh' | 'en') => void", description: '切换中英文输入模式' },
      { name: 'onSelectChinese', signature: '(word: string, appendText?: string) => void', description: '选择候选字词并回填到输入框' },
      { name: 'setActiveKeyboard', signature: '(keyboard: string) => void', description: '切换当前激活的键盘页签' },
      { name: 'onRecognition', signature: '(url: string) => Promise<void>', description: '触发图片识别并刷新候选列表' },
      { name: 'isKeyActive', signature: '(key: KeyboardAttributeType) => boolean', description: '用于给按键渲染激活态' },
    ],
    tokens: noTokens,
    renderDemo: UseInputDemo,
  },
  {
    key: 'use-continuous-trigger',
    path: '/hooks/use-continuous-trigger',
    title: 'useContinuousTrigger',
    menuLabel: 'useContinuousTrigger',
    description: '按下立即触发、长按持续触发的通用交互 hook，适合删除键、候选翻页和连续步进场景。',
    importCode: `import { useContinuousTrigger } from 'rc-virtual-keyboard';`,
    usageCode: `import { useState } from 'react';\nimport { useContinuousTrigger } from 'rc-virtual-keyboard';\n\nexport default function Demo() {\n  const [count, setCount] = useState(0);\n  const { startContinuousTrigger, stopContinuousTrigger } =\n    useContinuousTrigger<void>({\n      onTrigger: () => setCount((prev) => prev + 1),\n      delay: 280,\n      interval: 80,\n    });\n\n  return (\n    <button\n      onMouseDown={(e) => {\n        e.preventDefault();\n        startContinuousTrigger(undefined, 'mouse');\n      }}\n      onMouseUp={() => stopContinuousTrigger('mouse')}\n      onMouseLeave={() => stopContinuousTrigger('mouse')}\n    >\n      按住持续触发\n    </button>\n  );\n}`,
    props: [
      { name: 'onTrigger', type: '(payload: T) => void', defaultValue: '必填', description: '每次触发时执行的逻辑' },
      { name: 'delay', type: 'number', defaultValue: '1000', description: '开始连续触发前的等待时间' },
      { name: 'interval', type: 'number', defaultValue: '80', description: '连续触发间隔' },
    ],
    methods: [
      { name: 'startContinuousTrigger', signature: "(payload: T, source?: 'mouse' | 'touch') => void", description: '开始一次按下并注册长按触发' },
      { name: 'stopContinuousTrigger', signature: "(source?: 'mouse' | 'touch') => void", description: '结束当前触发会话' },
    ],
    tokens: noTokens,
    renderDemo: UseContinuousTriggerDemo,
  },
  {
    key: 'use-horizontal-drag-scroll',
    path: '/hooks/use-horizontal-drag-scroll',
    title: 'useHorizontalDragScroll',
    menuLabel: 'useHorizontalDragScroll',
    description: '给横向滚动容器增加鼠标/触摸拖拽能力，并在拖拽结束后短暂屏蔽误点击。',
    importCode: `import { useHorizontalDragScroll } from 'rc-virtual-keyboard';`,
    usageCode: `import { useRef } from 'react';\nimport { useHorizontalDragScroll } from 'rc-virtual-keyboard';\n\nexport default function Demo() {\n  const containerRef = useRef<HTMLDivElement>(null);\n  const dragScroll = useHorizontalDragScroll(containerRef);\n\n  return (\n    <div\n      ref={containerRef}\n      onMouseDown={dragScroll.onMouseDown}\n      onTouchStart={dragScroll.onTouchStart}\n    >\n      {/* 横向候选列表 */}\n    </div>\n  );\n}`,
    props: [
      { name: 'containerRef', type: 'React.RefObject<HTMLDivElement>', defaultValue: '必填', description: '目标横向滚动容器引用' },
    ],
    methods: [
      { name: 'onMouseDown', signature: '(event: React.MouseEvent<HTMLDivElement>) => void', description: '绑定到容器上，开启鼠标拖拽滚动' },
      { name: 'onTouchStart', signature: '(event: React.TouchEvent<HTMLDivElement>) => void', description: '绑定到容器上，开启触摸拖拽滚动' },
      { name: 'shouldIgnoreClick', signature: '() => boolean', description: '在 click 中判断当前是否应该屏蔽误触' },
    ],
    tokens: noTokens,
    renderDemo: UseHorizontalDragScrollDemo,
  },
  {
    key: 'use-touch-click-guard',
    path: '/hooks/use-touch-click-guard',
    title: 'useTouchClickGuard',
    menuLabel: 'useTouchClickGuard',
    description: '用于处理 touch 之后浏览器补发 click 的兼容问题，避免移动端组件被重复触发。',
    importCode: `import { useTouchClickGuard } from 'rc-virtual-keyboard';`,
    usageCode: `import { useTouchClickGuard } from 'rc-virtual-keyboard';\n\nexport default function Demo() {\n  const { markTouchInteraction, shouldIgnoreClick } = useTouchClickGuard();\n\n  return (\n    <button\n      onTouchStart={() => markTouchInteraction()}\n      onClick={() => {\n        if (shouldIgnoreClick()) return;\n        console.log('真正执行 click');\n      }}\n    >\n      移动端安全按钮\n    </button>\n  );\n}`,
    props: [],
    methods: [
      { name: 'markTouchInteraction', signature: '() => void', description: '在 touchstart / touchend 时标记一次触摸交互' },
      { name: 'shouldIgnoreClick', signature: '() => boolean', description: '在 click 回调中判断当前 click 是否应忽略' },
    ],
    tokens: noTokens,
    renderDemo: UseTouchClickGuardDemo,
  },
  {
    key: 'use-is-mobile',
    path: '/hooks/use-is-mobile',
    title: 'useIsMobile',
    menuLabel: 'useIsMobile',
    description: '基于 matchMedia 的设备判断 hook，用来决定默认布局是否切到移动端模式。',
    importCode: `import { useIsMobile } from 'rc-virtual-keyboard';`,
    usageCode: `import { useIsMobile } from 'rc-virtual-keyboard';\n\nexport default function Demo() {\n  const isMobile = useIsMobile('(max-width: 768px)');\n\n  return <div>{isMobile ? 'mobile' : 'desktop'}</div>;\n}`,
    props: [
      { name: 'query', type: 'string', defaultValue: '(max-width: 768px)', description: '自定义媒体查询表达式' },
    ],
    methods: [
      { name: 'return', signature: 'boolean', description: '当前媒体查询是否命中' },
    ],
    tokens: noTokens,
    renderDemo: UseIsMobileDemo,
  },
];
