import type { ComponentDoc } from './types';
import {
  EditKeyboardDemo,
  EmojiKeyboardDemo,
  FunctionKeyboardDemo,
  SettingKeyboardDemo,
  SymbolKeyboardDemo,
  WriteKeyboardDemo,
} from './demos';
import { sharedThemeTokens } from './shared';

export const panelComponentDocs: ComponentDoc[] = [
  {
    key: 'symbol-keyboard',
    path: '/components/symbol-keyboard',
    title: 'SymbolKeyboard',
    menuLabel: 'SymbolKeyboard',
    description: '按分类展示中英文、网络、数学、特殊与货币符号。',
    importCode: `import { SymbolKeyboard } from 'rc-virtual-keyboard';`,
    usageCode: `import { SymbolKeyboard } from 'rc-virtual-keyboard';\n\n<SymbolKeyboard\n  onClick={(key) => console.log('click', key.key)}\n  onKeyDown={(key) => console.log('down', key.code)}\n  onKeyUp={(key) => console.log('up', key.code)}\n/>;`,
    props: [
      { name: 'onClick', type: '(key) => void', defaultValue: '必填', description: '符号点击回调' },
      { name: 'onKeyDown / onKeyUp', type: '(key) => void', defaultValue: '-', description: '按下与抬起阶段回调' },
      { name: 'isKeyActive', type: '(key) => boolean', defaultValue: '-', description: '自定义激活态' },
    ],
    methods: [
      { name: 'onClick', signature: '(key: KeyboardAttributeType) => void', description: '点击任意符号时回调' },
      { name: 'onKeyDown / onKeyUp', signature: '(key: KeyboardAttributeType) => void', description: '按键生命周期回调' },
    ],
    tokens: sharedThemeTokens,
    renderDemo: SymbolKeyboardDemo,
  },
  {
    key: 'emoji-keyboard',
    path: '/components/emoji-keyboard',
    title: 'EmojiKeyboard',
    menuLabel: 'EmojiKeyboard',
    description: '内置常用、手势、爱心、动物、食物等 emoji 分类。',
    importCode: `import { EmojiKeyboard } from 'rc-virtual-keyboard';`,
    usageCode: `import { EmojiKeyboard } from 'rc-virtual-keyboard';\n\n<EmojiKeyboard\n  onClick={(key) => console.log('click', key.key)}\n  onKeyDown={(key) => console.log('down', key.code)}\n  onKeyUp={(key) => console.log('up', key.code)}\n/>;`,
    props: [
      { name: 'onClick', type: '(key) => void', defaultValue: '必填', description: 'emoji 选中回调' },
      { name: 'onKeyDown / onKeyUp', type: '(key) => void', defaultValue: '-', description: '按下与抬起阶段回调' },
      { name: 'isKeyActive', type: '(key) => boolean', defaultValue: '-', description: '自定义激活态' },
    ],
    methods: [
      { name: 'onClick', signature: '(key: KeyboardAttributeType) => void', description: '点击 emoji 时回调' },
      { name: 'onKeyDown / onKeyUp', signature: '(key: KeyboardAttributeType) => void', description: '按键生命周期回调' },
    ],
    tokens: sharedThemeTokens,
    renderDemo: EmojiKeyboardDemo,
  },
  {
    key: 'function-keyboard',
    path: '/components/function-keyboard',
    title: 'FunctionKeyboard',
    menuLabel: 'FunctionKeyboard',
    description: '用于触发 F1 到 F12 功能键。',
    importCode: `import { FunctionKeyboard } from 'rc-virtual-keyboard';`,
    usageCode: `import { FunctionKeyboard } from 'rc-virtual-keyboard';\n\n<FunctionKeyboard\n  onClick={(key) => console.log('click', key.code)}\n  onKeyDown={(key) => console.log('down', key.code)}\n  onKeyUp={(key) => console.log('up', key.code)}\n/>;`,
    props: [
      { name: 'onClick', type: '(key) => void', defaultValue: '-', description: '功能键点击回调' },
      { name: 'onKeyDown / onKeyUp', type: '(key) => void', defaultValue: '-', description: '按键按下与抬起回调' },
      { name: 'isKeyActive', type: '(key) => boolean', defaultValue: '-', description: '自定义激活态' },
    ],
    methods: [
      { name: 'onClick', signature: '(key: KeyboardAttributeType) => void', description: '点击 F1-F12 触发' },
      { name: 'onKeyDown / onKeyUp', signature: '(key: KeyboardAttributeType) => void', description: '按键生命周期回调' },
    ],
    tokens: sharedThemeTokens,
    renderDemo: FunctionKeyboardDemo,
  },
  {
    key: 'edit-keyboard',
    path: '/components/edit-keyboard',
    title: 'EditKeyboard',
    menuLabel: 'EditKeyboard',
    description: '光标控制与编辑动作面板，包含移动、选择、复制、粘贴等操作。',
    importCode: `import { EditKeyboard } from 'rc-virtual-keyboard';`,
    usageCode: `import { EditKeyboard } from 'rc-virtual-keyboard';\n\n<EditKeyboard\n  onClick={(key) => console.log('click', key.code)}\n  onKeyDown={(key) => console.log('down', key.code)}\n  onKeyUp={(key) => console.log('up', key.code)}\n/>;`,
    props: [
      { name: 'onClick', type: '(key) => void', defaultValue: '-', description: '编辑动作回调' },
      { name: 'onKeyDown / onKeyUp', type: '(key) => void', defaultValue: '-', description: '按下与抬起阶段回调' },
      { name: 'isKeyActive', type: '(key) => boolean', defaultValue: '-', description: '自定义激活态' },
    ],
    methods: [
      { name: 'onClick', signature: '(key: KeyboardAttributeType) => void', description: '点击移动、开始选择、复制、粘贴等操作时触发' },
      { name: 'onKeyDown / onKeyUp', signature: '(key: KeyboardAttributeType) => void', description: '按键生命周期回调' },
    ],
    tokens: sharedThemeTokens,
    renderDemo: EditKeyboardDemo,
  },
  {
    key: 'write-keyboard',
    path: '/components/write-keyboard',
    title: 'WriteKeyboard',
    menuLabel: 'WriteKeyboard',
    description: '手写板组件，支持画布输入、候选字词选择、清空与回车。',
    importCode: `import { WriteKeyboard } from 'rc-virtual-keyboard';`,
    usageCode: `import { WriteKeyboard } from 'rc-virtual-keyboard';\n\n<WriteKeyboard\n  chinese={['键', '盘']}\n  onSelectChinese={(word) => console.log(word)}\n  onRecognition={(url) => console.log(url)}\n  onClick={(key) => console.log('click', key.code)}\n  onKeyDown={(key) => console.log('down', key.code)}\n  onKeyUp={(key) => console.log('up', key.code)}\n/>;`,
    props: [
      { name: 'chinese', type: 'string[]', defaultValue: '必填', description: '候选汉字列表' },
      { name: 'onClick', type: '(key) => void', defaultValue: '-', description: '回车、删除、清空等功能键回调' },
      { name: 'onKeyDown / onKeyUp', type: '(key) => void', defaultValue: '-', description: '按下与抬起阶段回调' },
      { name: 'onSelectChinese', type: '(word: string) => void', defaultValue: '-', description: '选择候选字词时触发' },
      { name: 'onRecognition', type: '(url: string) => void', defaultValue: '-', description: '手写图像识别钩子' },
      { name: 'onMouseDown', type: '(event) => void', defaultValue: '-', description: '根节点 mouseDown 回调' },
      { name: 'isKeyActive', type: '(key) => boolean', defaultValue: '-', description: '自定义激活态' },
    ],
    methods: [
      { name: 'onSelectChinese', signature: '(word: string) => void', description: '候选字词选中回调' },
      { name: 'onRecognition', signature: '(dataUrl: string) => void', description: '需要接入识别服务时使用' },
      { name: 'onClick', signature: '(key: KeyboardAttributeType) => void', description: '清空、删除、回车等功能按键回调' },
      { name: 'onKeyDown / onKeyUp', signature: '(key: KeyboardAttributeType) => void', description: '按键生命周期回调' },
    ],
    tokens: sharedThemeTokens,
    renderDemo: WriteKeyboardDemo,
  },
  {
    key: 'setting-keyboard',
    path: '/components/setting-keyboard',
    title: 'SettingKeyboard',
    menuLabel: 'SettingKeyboard',
    description: '用于调整主题、位置、尺寸、字体和数字键布局的设置面板。',
    importCode: `import { SettingKeyboard } from 'rc-virtual-keyboard';`,
    usageCode: `import { SettingKeyboard } from 'rc-virtual-keyboard';\n\n<SettingKeyboard\n  themeMode="light"\n  positionMode="float"\n  vkbKeydownAudio="Y"\n  width="500px"\n  height="320px"\n  fontSize="14px"\n  fontFamily="'Microsoft YaHei', 'PingFang SC', sans-serif"\n  numberKeyboardLayoutMode="asc"\n  onWidthChange={(value) => console.log(value)}\n  onClick={(key) => console.log('click', key.code)}\n  onKeyDown={(key) => console.log('down', key.code)}\n  onKeyUp={(key) => console.log('up', key.code)}\n/>;`,
    props: [
      { name: 'themeMode', type: 'string', defaultValue: '必填', description: '当前主题模式' },
      { name: 'positionMode', type: 'string', defaultValue: '必填', description: '当前停靠位置模式' },
      { name: 'vkbKeydownAudio', type: 'string', defaultValue: '必填', description: '当前音效开关状态' },
      { name: 'width / height', type: 'string', defaultValue: '必填', description: '当前宽高' },
      { name: 'fontSize / fontFamily', type: 'string', defaultValue: '必填', description: '当前字体配置' },
      { name: 'numberKeyboardLayoutMode', type: "'asc' | 'desc'", defaultValue: '必填', description: '数字键布局模式' },
      { name: 'onWidthChange / onHeightChange', type: '(value: string) => void', defaultValue: '必填', description: '尺寸变化回调' },
      { name: 'onFontSizeChange / onFontFamilyChange', type: '(value: string) => void', defaultValue: '必填', description: '字体变化回调' },
      { name: 'onNumberKeyboardLayoutModeChange', type: "(mode: 'asc' | 'desc') => void", defaultValue: '-', description: '数字键布局切换回调' },
      { name: 'onClick', type: '(key) => void', defaultValue: '必填', description: '主题、位置、音效项点击回调' },
      { name: 'onKeyDown / onKeyUp', type: '(key) => void', defaultValue: '-', description: '按下与抬起阶段回调，仅作用于主题、位置、音效键项' },
    ],
    methods: [
      { name: 'onWidthChange / onHeightChange', signature: '(value: string) => void', description: '拖动滑块或点击尺寸步进按钮时触发' },
      { name: 'onFontSizeChange / onFontFamilyChange', signature: '(value: string) => void', description: '修改字体参数时触发' },
      { name: 'onNumberKeyboardLayoutModeChange', signature: "(mode: 'asc' | 'desc') => void", description: '数字键顺序切换回调' },
      { name: 'onClick', signature: '(key: KeyboardAttributeType) => void', description: '主题、位置、音效功能项点击回调' },
      { name: 'onKeyDown / onKeyUp', signature: '(key: KeyboardAttributeType) => void', description: '主题、位置、音效键项的按键生命周期回调' },
    ],
    tokens: sharedThemeTokens,
    renderDemo: SettingKeyboardDemo,
  },
];
